/**
 * Client for the repository / document analyzer extension (POST /api/analyze).
 *
 * Accepts either a public repo URL or pasted README / plan text and returns
 * a structured Markdown report generated by Gemini on the backend.
 */

export interface AnalyzeSource {
  kind: "github" | "url" | "text";
  label: string;
  repo_owner: string | null;
  repo_name: string | null;
  default_branch: string | null;
  files_sampled: number;
  readme_chars: number;
}

export interface AnalyzeResponse {
  report_markdown: string;
  source: AnalyzeSource;
  model: string;
}

export interface AnalyzeInput {
  repoUrl?: string;
  text?: string;
}

export async function analyzeProject(
  input: AnalyzeInput,
  signal?: AbortSignal,
): Promise<AnalyzeResponse> {
  const repoUrl = (input.repoUrl ?? "").trim();
  const text = (input.text ?? "").trim();

  if (!repoUrl && !text) {
    throw new Error("Paste a repo URL or project text to analyze.");
  }

  const res = await fetch("/api/analyze", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      repo_url: repoUrl || null,
      text: text || null,
    }),
    signal,
  });

  let body: unknown = {};
  try {
    body = await res.json();
  } catch {
    body = {};
  }
  const obj = body as Record<string, unknown>;

  if (!res.ok) {
    const detail = obj.detail;
    const msg =
      typeof detail === "string"
        ? detail
        : typeof obj.error === "string"
          ? obj.error
          : `Analyzer failed (${res.status}).`;
    throw new Error(msg);
  }

  if (typeof obj.report_markdown !== "string" || !obj.report_markdown.trim()) {
    throw new Error("Analyzer returned an empty report.");
  }

  return {
    report_markdown: obj.report_markdown,
    source: (obj.source ?? {
      kind: "text",
      label: "unknown",
      repo_owner: null,
      repo_name: null,
      default_branch: null,
      files_sampled: 0,
      readme_chars: 0,
    }) as AnalyzeSource,
    model: typeof obj.model === "string" ? obj.model : "gemini",
  };
}

/**
 * Extract the 1-line score from the "Quality Score" section produced by the
 * prompt. Returns `null` if the model didn't follow the format.
 */
export function extractScoreLine(markdown: string): string | null {
  const m = markdown.match(/Overall:\s*([0-9]+(?:\.[0-9]+)?\s*\/\s*10[^\n]*)/i);
  return m ? m[1].trim() : null;
}
